# Explicit distribution allowlist. Do not package unrelated local downloads.
# Keep this list in sync when adding/removing repository demo resources.
set(HPRENDERER_FULL_DEMO_ASSETS
    hdr/bloem_train_track_cloudy_4k.hdr
    hdr/ferndale_studio_12_4k.hdr
    hdr/glasshouse_interior_4k.hdr
    hdr/grasslands_sunset_4k.hdr
    hdr/modern_evening_street_4k.hdr
    hdr/newman_cafeteria_4k.hdr
    hdr/newport_loft.hdr
    models/baseball_01_4k/baseball_01.bin
    models/baseball_01_4k/baseball_01_4k.gltf
    models/baseball_01_4k/textures/baseball_01_arm_4k.jpg
    models/baseball_01_4k/textures/baseball_01_diff_4k.jpg
    models/baseball_01_4k/textures/baseball_01_nor_gl_4k.jpg
    models/blue_metal_plate_4k.gltf/blue_metal_plate.bin
    models/blue_metal_plate_4k.gltf/blue_metal_plate_4k.gltf
    models/blue_metal_plate_4k.gltf/textures/blue_metal_plate_arm_4k.jpg
    models/blue_metal_plate_4k.gltf/textures/blue_metal_plate_diff_4k.jpg
    models/blue_metal_plate_4k.gltf/textures/blue_metal_plate_nor_gl_4k.jpg
    models/interlocking/interlocking_concrete_pavers.bin
    models/interlocking/interlocking_concrete_pavers_4k.gltf
    models/interlocking/textures/interlocking_concrete_pavers_arm_4k.jpg
    models/interlocking/textures/interlocking_concrete_pavers_diff_4k.jpg
    models/interlocking/textures/interlocking_concrete_pavers_disp_4k.jpg
    models/interlocking/textures/interlocking_concrete_pavers_nor_gl_4k.jpg
    models/marble_bust_01_4k/marble_bust_01.bin
    models/marble_bust_01_4k/marble_bust_01_4k.gltf
    models/marble_bust_01_4k/textures/marble_bust_01_arm_4k.jpg
    models/marble_bust_01_4k/textures/marble_bust_01_diff_4k.jpg
    models/marble_bust_01_4k/textures/marble_bust_01_nor_gl_4k.jpg
    models/metal_office_desk_4k/metal_office_desk.bin
    models/metal_office_desk_4k/metal_office_desk_4k.gltf
    models/metal_office_desk_4k/textures/metal_office_desk_arm_4k.jpg
    models/metal_office_desk_4k/textures/metal_office_desk_diff_4k.jpg
    models/metal_office_desk_4k/textures/metal_office_desk_nor_gl_4k.jpg
    models/moon_01_4k.gltf/moon_01.bin
    models/moon_01_4k.gltf/moon_01_4k.gltf
    models/moon_01_4k.gltf/textures/moon_01_arm_4k.jpg
    models/moon_01_4k.gltf/textures/moon_01_diff_4k.jpg
    models/moon_01_4k.gltf/textures/moon_01_nor_gl_4k.jpg
    models/muddy_tracks_4k/muddy_tracks.bin
    models/muddy_tracks_4k/muddy_tracks_4k.gltf
    models/muddy_tracks_4k/textures/muddy_tracks_arm_4k.jpg
    models/muddy_tracks_4k/textures/muddy_tracks_diff_4k.jpg
    models/muddy_tracks_4k/textures/muddy_tracks_nor_gl_4k.jpg
    models/old_linoleum_flooring_01_4k/old_linoleum_flooring_01.bin
    models/old_linoleum_flooring_01_4k/old_linoleum_flooring_01_4k.gltf
    models/old_linoleum_flooring_01_4k/textures/old_linoleum_flooring_01_arm_4k.jpg
    models/old_linoleum_flooring_01_4k/textures/old_linoleum_flooring_01_diff_4k.jpg
    models/old_linoleum_flooring_01_4k/textures/old_linoleum_flooring_01_nor_gl_4k.jpg
    models/rusty_metal_grid_4k/rusty_metal_grid.bin
    models/rusty_metal_grid_4k/rusty_metal_grid_4k.gltf
    models/rusty_metal_grid_4k/textures/rusty_metal_grid_arm_4k.jpg
    models/rusty_metal_grid_4k/textures/rusty_metal_grid_diff_4k.jpg
    models/rusty_metal_grid_4k/textures/rusty_metal_grid_nor_gl_4k.jpg
    models/whitewashed_brick/textures/whitewashed_brick_arm_4k.jpg
    models/whitewashed_brick/textures/whitewashed_brick_diff_4k.jpg
    models/whitewashed_brick/textures/whitewashed_brick_disp_4k.jpg
    models/whitewashed_brick/textures/whitewashed_brick_nor_gl_4k.jpg
    models/whitewashed_brick/whitewashed_brick.bin
    models/whitewashed_brick/whitewashed_brick_4k.gltf
    textures/bricks2/bricks2.jpg
    textures/bricks2/bricks2_disp.jpg
    textures/bricks2/bricks2_normal.jpg
    textures/wood.png
)
